### ISSUE TITLE
Impossible d'être un héro 2 fois de suite

### ISSUE THREAD

**Issue by Kykka90** [LucasTaddei/FakeNewsRealBruise#3]
Lorsque le joueur ou la joueuse ne clique sur aucune flèche, une page arrive pour le féliciter de ne pas s'être fait avoir par le système. Si celui.celle-ci essait de reproduire le même scénario en ne cliquant pas, la fonction qui doit le rediriger vers l'autre page ne fonctionne pas.

**Comment by LeaKiller** [comment]
Problème résolu en déplaçant le code d'initialisation des variables du constructeur de la classe vers la fonction preload().
