### ISSUE TITLE
Bruits continuent lors qu'on restart le jeu

### ISSUE THREAD

**Issue by LucasTaddei** [LucasTaddei/FakeNewsRealBruise#4]
Quand on recommence l'expérience, les sons de la session precedente ne s'arrêtent pas. On a essayé avec plusieurs fonctions de _restart_, mais sans résultat.

**Comment by LeaKiller** [comment]
Problème corrigé. Fin de la chanson à la fin de la scène, chargement d'une nouvelle chanson pour les scènes de fin de jeu. Chanson réinitialisée en début de partie.
