### ISSUE TITLE
On peut tricher en gardant les flèches appuyées

### ISSUE THREAD

**Issue by LucasTaddei** [LucasTaddei/FakeNewsRealBruise#5]
On a pas réussi à intégrer la contrainte qui oblige à appuyer sur la flèche QUE au bon moment, en rendant erreur tous les autres instances.

**Comment by LeaKiller** [comment]
Prise en compte de la touche enfoncée seulement pendant un temps limité (this.keyDownDelay) pour éviter de pouvoir la maintenir indéfiniment et capturer toutes les flèches.

`if (isSpaceKeyPressed && (new Date().getTime() - this.lastSpaceBarPressedAt >= this.keyDownDelay))`
